# Generated by Django 5.0.7 on 2024-07-21 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='main/static/assets/img/about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='subtitle',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='count',
            name='icon',
            field=models.CharField(choices=[('bi bi-diagram-3', 'Years of Experience'), ('bi bi-award', 'Awards Won'), ('bi bi-journal-code', 'Projects Completed'), ('bi bi-people', 'Clients Collaborated'), ('bi bi-briefcase', 'Jobs'), ('bi bi-gear', 'Skills'), ('bi bi-calendar', 'Events'), ('bi bi-globe', 'Global Reach')], max_length=100),
        ),
        migrations.AlterField(
            model_name='interest',
            name='icon',
            field=models.CharField(choices=[('ri-anchor-line', 'Marine Engineering'), ('ri-computer-line', 'Web Development'), ('ri-paint-brush-line', 'Graphic Design'), ('ri-bar-chart-box-line', 'Data Analytics'), ('ri-lightbulb-line', 'AI'), ('ri-database-2-line', 'Blockchain Technology'), ('ri-rocket-line', 'Space Exploration'), ('ri-store-line', 'Entrepreneurship'), ('ri-football-line', 'Rugby'), ('ri-history-line', 'History'), ('ri-flask-line', 'Science'), ('ri-newspaper-line', 'Current Affairs'), ('ri-book-line', 'Education'), ('ri-music-line', 'Music'), ('ri-game-line', 'Gaming'), ('ri-camera-line', 'Photography')], max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='main/static/assets/img/testimonials/'),
        ),
    ]
