# Generated by Django 5.0.7 on 2024-07-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_about_image_alter_about_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(upload_to='static/assets/img/about/'),
        ),
        migrations.AlterField(
            model_name='count',
            name='icon',
            field=models.CharField(choices=[('bi bi-award', 'Award'), ('bi bi-cup', 'Cup'), ('bi bi-people', 'People'), ('bi bi-clock', 'Clock'), ('bi bi-star', 'Star'), ('bi bi-gear', 'Gear'), ('bi bi-briefcase', 'Briefcase'), ('bi bi-calendar', 'Calendar'), ('bi bi-trophy', 'Trophy'), ('bi bi-heart', 'Heart'), ('bi bi-globe', 'Globe')], max_length=100),
        ),
        migrations.AlterField(
            model_name='interest',
            name='icon',
            field=models.CharField(choices=[('ri-anchor-line', 'Marine Engineering'), ('ri-computer-line', 'Web Development'), ('ri-paint-brush-line', 'Graphic Design'), ('ri-bar-chart-box-line', 'Data Analytics'), ('ri-lightbulb-line', 'AI'), ('ri-database-2-line', 'Blockchain Technology'), ('ri-rocket-line', 'Space Exploration'), ('ri-store-line', 'Entrepreneurship'), ('ri-football-line', 'Rugby'), ('ri-history-line', 'History'), ('ri-flask-line', 'Science'), ('ri-newspaper-line', 'Current Affairs')], max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='static/assets/img/testimonials/'),
        ),
    ]
