# Generated by Django 5.0.7 on 2024-07-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_about_image_alter_count_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='color',
            field=models.CharField(choices=[('#ffbb2c', 'Marine Engineering'), ('#e80368', 'Web Development'), ('#e361ff', 'Graphic Design'), ('#5578ff', 'Data Analytics'), ('#ffa76e', 'AI'), ('#47aeff', 'Blockchain Technology'), ('#e74c3c', 'Space Exploration'), ('#4233ff', 'Entrepreneurship'), ('#f39c12', 'Rugby'), ('#3498db', 'History'), ('#e74c3c', 'Science'), ('#2ecc71', 'Current Affairs')], default='#ffbb2c', max_length=7),
        ),
        migrations.AlterField(
            model_name='interest',
            name='icon',
            field=models.CharField(choices=[('ri-anchor-line', 'Marine Engineering'), ('ri-computer-line', 'Web Development'), ('ri-paint-brush-line', 'Graphic Design'), ('ri-bar-chart-box-line', 'Data Analytics'), ('ri-lightbulb-line', 'AI'), ('ri-database-2-line', 'Blockchain Technology'), ('ri-rocket-line', 'Space Exploration'), ('ri-store-line', 'Entrepreneurship'), ('ri-football-line', 'Rugby'), ('ri-history-line', 'History'), ('ri-flask-line', 'Science'), ('ri-newspaper-line', 'Current Affairs')], default='ri-anchor-line', max_length=100),
        ),
    ]
