# Generated by Django 5.0.7 on 2024-07-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_interest_color_alter_interest_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('#e361ff', 'HTML'), ('#5578ff', 'CSS'), ('#e74c3c', 'JavaScript'), ('#4233ff', 'Python'), ('#f39c12', 'Django'), ('#3498db', 'WordPress/CMS'), ('#e74c3c', 'Bootstrap'), ('#2ecc71', 'Vue.js'), ('#ffbb2c', 'React.js')], default='#18d26e', max_length=7),
        ),
    ]
