# Generated by Django 5.0.7 on 2024-07-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='VoluntaryExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='interest',
            name='color',
            field=models.CharField(choices=[('#18d26e', 'Default'), ('#ffbb2c', 'Marine Engineering'), ('#e80368', 'Web Development'), ('#e361ff', 'Graphic Design'), ('#5578ff', 'Data Analytics'), ('#ffa76e', 'AI'), ('#47aeff', 'Blockchain Technology'), ('#e74c3c', 'Space Exploration'), ('#4233ff', 'Entrepreneurship'), ('#f39c12', 'Rugby'), ('#3498db', 'History'), ('#e74c3c', 'Science'), ('#2ecc71', 'Current Affairs')], default='#18d26e', max_length=7),
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('#18d26e', 'Default'), ('#e361ff', 'HTML'), ('#5578ff', 'CSS'), ('#e74c3c', 'JavaScript'), ('#4233ff', 'Python'), ('#f39c12', 'Django'), ('#3498db', 'WordPress/CMS'), ('#e74c3c', 'Bootstrap'), ('#2ecc71', 'Vue.js'), ('#ffbb2c', 'React.js'), ('#3498db', 'Canva')], default='#18d26e', max_length=7),
        ),
    ]
