# Generated by Django 5.0.7 on 2024-07-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_education_professionalexperience_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('bx bx-laptop', 'Laptop'), ('bx bx-chalkboard', 'Chalkboard'), ('bx bx-file', 'File'), ('bx bx-paint', 'Paint'), ('bx bxl-css3', 'CSS3'), ('bx bx-line-chart', 'Line Chart'), ('bx bx-cube', 'Cube'), ('bx bx-folder', 'Folder'), ('bx bxl-wordpress', 'WordPress')], default='bx bx-laptop', max_length=50)),
                ('color', models.CharField(choices=[('#007bff', 'Blue'), ('#28a745', 'Green'), ('#ffc107', 'Yellow'), ('#dc3545', 'Red'), ('#17a2b8', 'Teal'), ('#fd7e14', 'Orange'), ('#6f42c1', 'Purple'), ('#20c997', 'Cyan'), ('#0073aa', 'Dark Blue')], default='#007bff', max_length=7)),
                ('description', models.TextField()),
            ],
        ),
    ]
