# Generated by Django 5.0.7 on 2024-07-22 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_portfolio_banner_portfolio_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='banner',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_banner',
            field=models.ImageField(default='static/assets/img/portfolio/default-details-1.jpg', upload_to='static/assets/img/portfolio/banner/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='service_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service'),
        ),
    ]
