# Generated by Django 5.0.7 on 2024-07-22 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_portfolio_banner_portfolio_portfolio_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='portfolio_banner',
        ),
        migrations.CreateModel(
            name='PortfolioBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/assets/img/portfolio/default-details-1.jpg', upload_to='static/assets/img/portfolio/banner/')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='main.portfolio')),
            ],
        ),
    ]
