# Generated by Django 5.0.7 on 2024-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_portfolio_portfolio_banner_portfoliobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliobanner',
            name='image',
            field=models.ImageField(default='static/assets/img/portfolio/default-details-1.jpg', upload_to='static/assets/img/portfolio/'),
        ),
    ]
